# docker-compose.yaml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/webstudio
      DIRECT_URL:   postgresql://user:pass@db:5432/webstudio
    networks:
      - shared-network

networks:
  shared-network:
    external: true
